#here we store configuration data or hyperparameter tunners so that we can tune it directly from here only
data_injection:
  test_size: 0.21
feature_engineering:
  max_features: 15
model_building:
  n_estimators: 12
  learning_rate: 0.1
